seq_length: 49152
learning_rate: 3e-5
train_batch_size: 32
num_individuals_per_gene: 128
alpha: 0.5
experiment_name: "FinalPaperWholeBlood_discrete_str"
max_epochs: 100
precision: bf16-mixed
tissues_to_train: "Whole Blood"
gradient_clip_val: 0.05
seed: 0
mask_dna_prop: 0
discretize_bins: 5
contrast_embed: 0
stratify_expr: 32
