seq_length: 49152
learning_rate: 1e-5
train_batch_size: 24
num_individuals_per_gene: 24
alpha: 0.5
experiment_name: "shift_diff_lr_multi_attn"
max_epochs: 20
precision: bf16-mixed
tissues_to_train: "Whole Blood"
gradient_clip_val: 0.05
seed: 0
mask_dna_prop: 0
discretize_bins: 0
contrast_embed: 1
stratify_expr: 0
residual_expr: 0
raw_expr: 1
gene_embed: 0
atten_pool: 1
attn_dim: 1024
attn_heads: 4
shift: 100
reverse_complement: 0
train_gene_file: "1000_train_genes.txt"
