seq_length: 12288
learning_rate: 5e-6
pct_start: 0.1
final_div_factor: 10
train_batch_size: 4
num_individuals_per_gene: 4
alpha: 0.5
experiment_name: "test"
max_epochs: 3
precision: bf16-mixed
tissues_to_train: "blood,muscle,adipose"
gradient_clip_val: 0.05
seed: 0
version: 0
mask_dna_prop: 0
discretize_bins: 0
contrast_embed: 0
stratify_expr: 0
residual_expr: 0
predict_expr: 1
raw_expr: 0
gene_embed: 0
eQTL_guided: 0
atten_pool: 0
attn_dim: 256
attn_heads: 2
shift: 100
shift_freq: 0.5
reverse_complement: 0
rc_freq: 0
train_gene_file: "train_filter_egenes_5K.txt"
val_gene_file: "val_filter_egenes_1K.txt"
test_gene_file: "test_filter_egenes_2K.txt"
expression_filepath: "predicted_gene_expression"